#pragma once
#include "matrix_filter.h"
#include "sharpening_filter.h"
#include "negative_filter.h"
#include "grayscale_filter.h"
#include "crop_filter.h"
#include "edge_detection_filter.h"
#include "gaussian_blur_filter.h"
#include "my_own_filter.h"